package com.lurodev.ApiGestionInspecciones.Entities;

public enum ProjectStates {
    APROBADO,
    DOCUMENTACION_INICIAL,
    DOCUMENTACION_INICIAL_APROBADA,
    EN_PROGRAMACION,
    PROGRAMADO,
    INSPECTOR,
    APROBADO_INSPECTOR,
    RECHAZADO_INSPECTOR,
    ANALISTA_TECNICO,
    APROBADO_AREA_TECNICA,
    RECHAZADO_AREA_TECNICA,
    EN_EMISION,
    ABIERTO,
    CERRADO
}
